#!/usr/bin/python

from PIL import Image
from os.path import abspath, exists
from sys import argv, exit

usage = """
The screencons of two images is their horizontal juxtaposition after the taller 
image has been resized to match the height of the shorter image.

Usage:
    screencons <left-image-file> <right-image-file> <destination-file>

The left and right image files must already exist; the destination file must
not. Common image file formats are supported (.png, .jpg, etc.).

The extension of the destination file determines the file format ('out.jpg' will
be a JPEG, etc.).
"""

if len(argv) != 4:
    print usage
    exit()

leftFile = abspath(argv[1])
rightFile = abspath(argv[2])
outputFile = abspath(argv[3])

if exists(outputFile):
    print "I'd rather you didn't use me to overwrite an existing image file."
    print outputFile + " already exists."
    print usage
    exit()

leftImage = Image.open(leftFile)
rightImage = Image.open(rightFile)

outputHeight = min(leftImage.height, rightImage.height)


def resized(image):
    if image.height == outputHeight:
        return image
    else:
        outputWidth = int(float(image.width) * float(outputHeight) / float(image.height))
        return image.resize((outputWidth, outputHeight))


def juxtapose(left, right):
    juxtaposition = Image.new('RGBA', (left.width + right.width, max(left.height, right.height)))

    juxtaposition.paste(left, (0, 0))
    juxtaposition.paste(right, (left.width, 0))

    return juxtaposition


outputImage = juxtapose(resized(leftImage), resized(rightImage))

outputImage.save(outputFile)
